# numpy:

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = a ** 2 + b ** 3
c

array([126, 220, 352, 528], dtype=int32)

In [3]:
a

array([1, 2, 3, 4])

## ndarray

axis(轴):数据的维度

rank(秩):轴的数量

### 基本属性:
![image.png](./imgs/Snipaste_2020-03-29_01-00-29.png)

In [4]:
a.ndim

1

In [5]:
a.shape

(4,)

In [6]:
a.size

4

In [7]:
a.dtype

dtype('int32')

In [8]:
a.itemsize

4

### ndarray的元素类型:
![image.png](./imgs/Snipaste_2020-03-29_01-04-29.png)
![image.png](./imgs/Snipaste_2020-03-29_01-05-11.png)
![image.png](./imgs/Snipaste_2020-03-29_01-05-31.png)

### ndarray创建方法:
![image.png](./imgs/Snipaste_2020-03-29_01-12-54.png)
![image.png](./imgs/Snipaste_2020-03-29_01-16-31.png)

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeros([3, 3], dtype=np.float32)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [11]:
np.ones([3, 3], dtype=np.float32)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [16]:
np.full(shape=[3, 3], fill_value=3.14, dtype=np.float32)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]], dtype=float32)

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.zeros_like(a)

array([0, 0, 0, 0])

In [20]:
np.ones_like(b)

array([1, 1, 1, 1])

In [22]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### ndarray改变维度
![image.png](./imgs/Snipaste_2020-03-29_01-21-26.png)

In [23]:
x = np.ones([2, 2, 2])
x

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [24]:
x.reshape([2, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
x.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1.])

### ndarray.astype(): 更换数据类型

会创建新数组,不修改原数组

In [26]:
x.astype(np.int32)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

### ndarray.tolist: 转为列表

In [27]:
x.tolist()

[[[1.0, 1.0], [1.0, 1.0]], [[1.0, 1.0], [1.0, 1.0]]]

### ndarray索引和切片

In [30]:
a = np.zeros([3, 3, 3])
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
a[0], a[0, 0], a[0, 0, 0]

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([0., 0., 0.]),
 0.0)

In [34]:
a[0, 0, 0:2:2]

array([0.])

In [35]:
b = np.arange(64).reshape(4, 4, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [39]:
b[0, 0, ::2]

array([0, 2])

In [40]:
b[:, :, ::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]],

       [[32, 34],
        [36, 38],
        [40, 42],
        [44, 46]],

       [[48, 50],
        [52, 54],
        [56, 58],
        [60, 62]]])

In [41]:
b[..., ::2]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10],
        [12, 14]],

       [[16, 18],
        [20, 22],
        [24, 26],
        [28, 30]],

       [[32, 34],
        [36, 38],
        [40, 42],
        [44, 46]],

       [[48, 50],
        [52, 54],
        [56, 58],
        [60, 62]]])

### ndarray的一元函数计算
![image.png](./imgs/Snipaste_2020-03-29_01-37-05.png)

In [42]:
b.mean()

31.5

In [43]:
b / b.mean()

array([[[0.        , 0.03174603, 0.06349206, 0.0952381 ],
        [0.12698413, 0.15873016, 0.19047619, 0.22222222],
        [0.25396825, 0.28571429, 0.31746032, 0.34920635],
        [0.38095238, 0.41269841, 0.44444444, 0.47619048]],

       [[0.50793651, 0.53968254, 0.57142857, 0.6031746 ],
        [0.63492063, 0.66666667, 0.6984127 , 0.73015873],
        [0.76190476, 0.79365079, 0.82539683, 0.85714286],
        [0.88888889, 0.92063492, 0.95238095, 0.98412698]],

       [[1.01587302, 1.04761905, 1.07936508, 1.11111111],
        [1.14285714, 1.17460317, 1.20634921, 1.23809524],
        [1.26984127, 1.3015873 , 1.33333333, 1.36507937],
        [1.3968254 , 1.42857143, 1.46031746, 1.49206349]],

       [[1.52380952, 1.55555556, 1.58730159, 1.61904762],
        [1.65079365, 1.68253968, 1.71428571, 1.74603175],
        [1.77777778, 1.80952381, 1.84126984, 1.87301587],
        [1.9047619 , 1.93650794, 1.96825397, 2.        ]]])

In [45]:
b.var()

341.25

In [46]:
b.std()

18.472953201911167

### ndarray的一元函数计算
![image.png](./imgs/Snipaste_2020-03-29_01-39-33.png)

In [47]:
a = np.arange(64).reshape(4, 4, 4)
b = np.arange(64).reshape(4, 4, 4)
a, b

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],
 
        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],
 
        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],
 
        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],
 
        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]]))

In [48]:
np.maximum(a, b)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [49]:
np.mod(a, b)

c:\programdata\anaconda3\envs\tf2notebook\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

### ndarray的文件存取

In [50]:
np.savez('array_archive.npz', a=a, b=b)

In [52]:
file = np.load('array_archive.npz')

In [58]:
file['a'], file['b']

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],
 
        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],
 
        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]],
 
        [[16, 17, 18, 19],
         [20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31]],
 
        [[32, 33, 34, 35],
         [36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]],
 
        [[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59],
         [60, 61, 62, 63]]]))

### ndarray伪随机数生成
![image.png](./imgs/Snipaste_2020-03-29_01-52-51.png)
![image.png](./imgs/Snipaste_2020-03-29_01-54-02.png)
![image.png](./imgs/Snipaste_2020-03-29_01-55-17.png)

In [61]:
samples = np.random.normal(size=[2, 2, 2])
samples

array([[[ 2.04837833, -0.48526885],
        [ 1.46968931, -0.82707701]],

       [[ 1.08171709,  1.45427789],
        [-0.43355049, -2.39485666]]])

In [65]:
# 全局随机种子
np.random.seed(666)
np.random.random([2, 2])

array([[0.70043712, 0.84418664],
       [0.67651434, 0.72785806]])

In [62]:
# 局部随机种子
rng = np.random.RandomState(1234)
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

### ndarray的统计函数
![image.png](./imgs/Snipaste_2020-03-29_01-57-14.png)
![image.png](./imgs/Snipaste_2020-03-29_01-58-24.png)

In [66]:
b.var()

341.25

In [67]:
b.std()

18.472953201911167

In [68]:
np.argmax(a), np.argmin(x)

(63, 0)

In [70]:
np.unravel_index(np.argmax(x), x.shape)

(0, 0, 0)

In [71]:
np.gradient(samples)

[array([[[-0.96666125,  1.93954673],
         [-1.9032398 , -1.56777965]],
 
        [[-0.96666125,  1.93954673],
         [-1.9032398 , -1.56777965]]]),
 array([[[-0.57868903, -0.34180817],
         [-0.57868903, -0.34180817]],
 
        [[-1.51526758, -3.84913455],
         [-1.51526758, -3.84913455]]]),
 array([[[-2.53364718, -2.53364718],
         [-2.29676632, -2.29676632]],
 
        [[ 0.3725608 ,  0.3725608 ],
         [-1.96130616, -1.96130616]]])]

In [72]:
from PIL import Image

In [74]:
img = np.array(Image.open('./imgs/Snipaste_2020-03-29_01-58-24.png'))
img.shape

(258, 733, 3)

In [75]:
img.dtype

dtype('uint8')

In [76]:
b = [255, 255, 255] - img
b

array([[[149, 156, 118],
        [152, 158, 120],
        [149, 154, 116],
        ...,
        [146, 154, 119],
        [145, 153, 118],
        [149, 156, 121]],

       [[149, 156, 118],
        [153, 159, 121],
        [150, 156, 118],
        ...,
        [153, 160, 129],
        [153, 160, 128],
        [149, 155, 122]],

       [[149, 156, 119],
        [150, 156, 119],
        [151, 157, 122],
        ...,
        [143, 149, 122],
        [142, 148, 120],
        [147, 153, 122]],

       ...,

       [[144, 152, 114],
        [141, 150, 112],
        [143, 152, 114],
        ...,
        [141, 150, 112],
        [142, 151, 113],
        [143, 152, 114]],

       [[143, 152, 114],
        [144, 153, 115],
        [144, 153, 115],
        ...,
        [146, 154, 116],
        [146, 154, 116],
        [142, 151, 113]],

       [[144, 152, 115],
        [144, 152, 115],
        [144, 152, 115],
        ...,
        [145, 153, 116],
        [142, 151, 113],
        [147, 155, 118]]

In [77]:
img = Image.fromarray(b.astype('uint8'))
img.save('1.jpg')

In [79]:
img = np.array(Image.open('./imgs/Snipaste_2020-03-29_01-58-24.png').convert('L'))
b = 255 - img
b

array([[150, 152, 148, ..., 148, 147, 150],
       [150, 153, 150, ..., 154, 154, 149],
       [150, 150, 151, ..., 144, 143, 148],
       ...,
       [145, 143, 145, ..., 143, 144, 145],
       [145, 146, 146, ..., 147, 147, 144],
       [145, 145, 145, ..., 146, 144, 148]], dtype=uint8)

In [80]:
img = Image.fromarray(b.astype('uint8'))
img.save('2.jpg')

In [84]:
img = np.array(Image.open('./imgs/Snipaste_2020-03-29_01-58-24.png').convert('L'))
b = (100 / 255) * img + 150
img = Image.fromarray(b.astype('uint8'))
img.save('3.jpg')

## 手绘风格图片变换

In [88]:
img = np.array(Image.open('./imgs/Snipaste_2020-03-29_02-49-10.png').convert('L')).astype('float')

In [89]:
depth = 10
grad = np.gradient(img)
grad_x, grad_y = grad

In [90]:
grad_x = grad_x * depth / 100
grad_y = grad_y * depth / 100
A = np.sqrt(grad_x ** 2 + grad_y ** 2 + 1)

In [91]:
uni_x = grad_x / A
uni_y = grad_y / A
uni_z = 1. / A

In [92]:
vec_el = np.pi / 2.2
vec_az = np.pi / 4.

In [93]:
dx = np.cos(vec_el) * np.cos(vec_az)
dy = np.cos(vec_el) * np.sin(vec_az)
dz = np.sin(vec_el)

In [94]:
b = 255 * (dx * uni_x + dy * uni_y + dz * uni_z)
b = b.clip(0, 255)

In [95]:
img = Image.fromarray(b.astype('uint8'))
img.save('4.jpg')