In [121]:
# numpy 补充
import numpy as np
a = np.nan
# b = np.inf
# print(a,type(a))
# print(b,type(b))

# --判断数组中为nan的个数(注意：float类型的数据才能赋值nan)
# t = np.arange(24,dtype=float).reshape(4,6)
# print(t)

# 可以使用np.count_nonzero() 来判断非零的个数  
# print(np.count_nonzero(t))

# t[3,4] = np.nan
# # 两个 nan之间是不相等的
# # print(np.nan != np.nan) ->True  1
# print(np.count_nonzero(t != t))

# # print(np.sum(t,axis=0))
# # print(np.isnan(t))
# # 将nan替换为0
# t[np.isnan(t)] = 0
# print(t)

# -------------
t = np.arange(24).reshape(4,6).astype('float')

# 将数组中的一部分替换nan
t[1,3:] = np.nan
print(t)
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]): 
	#获取当前列数据
	temp_col = t[:,i]

	# 判断当前列的数据中是否含有nan
	nan_num = np.count_nonzero(temp_col != temp_col)

	if nan_num != 0: # 条件成立说明含有nan

		# 将这一列不为nan的数据拿出来
		temp_col_not_nan = temp_col[temp_col==temp_col]

		# 将nan替换成这一列的平均值
		temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)

print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [150]:
# pandas
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
# 一维的数组
# sel = Series([1,2,3,4])
# print(sel)

# 通常我们会自己创建索引
# sel =  Series(data = [1,2,3,4],index=['a','b','c','d'])
sel =  Series(data = [1,2,3,4], index = list('abcd'))
# print(sel.values)

# print(sel.index)
# 获取索引和值对
# print(list(sel.iteritems()))

# print(sel)

# 将字典转换为Series
# dict={"red":100,"black":400,"green":300,"pink":900}
# se3=Series(dict)
# print(se3)

# Series数据获取
# sel =  Series(data = [1,2,3,4], index = list('abcd'))
# print(sel)

# Series对象同时支持位置和标签两种方式获取数据
# print('索引下标',sel['c'])
# print('位置下标',sel[2])

# 获取不连续的数据
# print('索引下标',sel[['a','c']])
# print('位置下标',sel[[1,3]])

# # 可以使用切片或取数据
# print('位置切片',sel[1:3])# 左包含右不包含
# print('索引切片',sel['b':'d'])# 左右都包含

# 重新赋值索引的值
# sel.index = list('dcba')
# print(sel)
# # ReIndex重新索引,会返回一个新的Series(调用reindex将会重新排序，缺失值则用NaN填补)
# result = sel.reindex(['b','a','c','d','e'])
# print(result)
# se1=pd.Series(range(10,15))
# print(se1)
# drop有没有返回值呢 有1 没有2
# result = se1.drop([2,3])  # 没有的话  None   有： 结果
# print(se1.drop([2,3]))


# series1 = pd.Series([1,2,3,4],['London','HongKong','Humbai','lagos'])
# series2 = pd.Series([1,3,6,4],['London','Accra','lagos','Delhi'])
# print(series1)
# print(series2)
# print(series1-series2)
# print(series1+series2)
# print(series1*series2)

# sel =  Series(data = [1,6,3,5], index = list('abcd'))
# print(sel)
# print(sel[sel>3]) # 布尔数组过滤
# print(sel*2) # 标量乘法
# print(np.square(sel)) # 可以直接加入到numpy的数学函数



a    1
b    6
c    3
d    5
dtype: int64
a     1
b    36
c     9
d    25
dtype: int64


In [152]:
# 使用二维数组
df1 = DataFrame(np.random.randint(0,10,(4,4)),index=[1,2,3,4],columns=['a','b','c','d'])
print(df1)

   a  b  c  d
1  7  3  5  5
2  2  2  5  0
3  0  2  8  6
4  1  7  9  7


In [156]:
dict={
    'Province': ['Guangdong', 'Beijing', 'Qinghai', 'Fujian'],
    'pop': [1.3, 2.5, 1.1, 0.7],
    'year': [2018, 2018, 2018, 2018]}
df2=pd.DataFrame(dict,index=[1,2,3,4])
# print(df2)

# 使用from_dict
# dict2={"a":[1,2,3],"b":[4,5,6]}
# df6=pd.DataFrame.from_dict(dict2)
# print(df6)

data = {
    'Name':pd.Series(['zs','ls','we'],index=['a','b','c']),
    'Age':pd.Series(['10','20','30','40'],index=['a','b','c','d']),
    'country':pd.Series(['中国','日本','韩国'],index=['a','c','b'])
}

df = pd.DataFrame(data)
print(df)

  Name Age country
a   zs  10      中国
b   ls  20      韩国
c   we  30      日本
d  NaN  40     NaN


In [176]:
# dataframe常用属性
df_dict = {
	'name':['James','Curry','Iversion'],
	'age':['18','20','19'],
	'national':['us','China','us']
}
df = pd.DataFrame(data=df_dict,index=['0','1','2'])
print(df)
# 获取行数和列数
# print(df.shape)

# # # 获取行索引
# print(df.index.tolist())

# # # 获取列索引
# print(df.columns.tolist())

# # 获取数据的类型
# print(df.dtypes)

# # 获取数据的维度
# print(df.ndim)

# print(df.info())

#  显示头几行,默认显示5行
# print(df.head(2))

# 显示后几行
# print(df.tail(1))


# 获取DataFrame的列

# print(df['name'])


#因为我们只获取一列，所以返回的就是一个 Series
# print(type(df['name']))


# 如果获取多个列，那返回的就是一个 DataFrame 类型：
# print(df[['name','age']])
# print(type(df[['name','age']]))

# 获取一行
# print(df[0:1])

# # 去多行
# print(df[1:3])

# 取多行里面的某一列（不能进行多行多列的选择）
# print(df[1:3][['name','age']])

# df[1:3][['name','age']]

       name age national
0     James  18       us
1     Curry  20    China
2  Iversion  19       us
       name age
1     Curry  20
2  Iversion  19


In [184]:
# 获取某一行某一列的数据 (索引)index=['0','1','2']
# print(df.loc['0','name'])

# 一行所有列
# print(df.loc['0',:])

# print(df.loc['0',['name','age']])

# print(df.loc[['0','2'],['name','national']])


# df.iloc  (位置信息)

# print(df.iloc[1])
# print(df.iloc[0:2])

# print(df.iloc[[0,2],:])

# print(df.iloc[1,0])



       name age national
0     James  18       us
2  Iversion  19       us
Curry
